package ru.darujo.hash;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

// Java program to calculate SHA hash value

public class HashService {
    public static byte[] getSHA(String input) throws NoSuchAlgorithmException {
        return getHash(input, "SHA-256");
    }

    public static byte[] getMD5Hash(String input) throws NoSuchAlgorithmException {
        return getHash(input, "MD5");
    }

    public static byte[] getHash(String input, String typeHash) throws NoSuchAlgorithmException {
        // Static getInstance method is called with hashing SHA
        MessageDigest md = MessageDigest.getInstance(typeHash);

        // digest() method called
        // to calculate message digest of an input
        // and return array of byte
        return md.digest(input.getBytes(StandardCharsets.UTF_8));
    }

    public static String toHexString(byte[] hash) {
        // Convert byte array into signum representation
        BigInteger number = new BigInteger(1, hash);

        // Convert message digest into hex value
        StringBuilder hexString = new StringBuilder(number.toString(16));

        // Pad with leading zeros
        while (hexString.length() < 64) {
            hexString.insert(0, '0');
        }

        return hexString.toString();
    }

    public static String getSHA256(String text) {
        try {
            return toHexString(getSHA(text));
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    public static String getMD5(String text) {
        try {
            return toHexString(getMD5Hash(text));
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }


    // Driver code
//    public static void main(String[] args)
//    {
//        try
//        {
//            System.out.println("HashCode Generated by SHA-256 for:");
//
//            String s1 = "ndflbroker:990.00:12:kOGpnJ35xkTji5mO6mR4-test";
//            System.out.println("\n" + s1 + " : " + getSHA256(s1));
//            System.out.println("\n" + s1 + " : " + getMD5(s1));
//
//            String s2 = "hello world";
//            System.out.println("\n" + s2 + " : " + toHexString(getSHA(s2)));
//
//            String s3 = "K1t4fo0V";
//            System.out.println("\n" + s3 + " : " + toHexString(getSHA(s3)));
//        }
//        // For specifying wrong message digest algorithms
//        catch (NoSuchAlgorithmException e) {
//            System.out.println("Exception thrown for incorrect algorithm: " + e);
//        }
//    }
}