-- Table: work_time_project.work_project

-- DROP TABLE IF EXISTS work_time_project.work_project;

CREATE TABLE IF NOT EXISTS work_time_project.work_project
(
    id                   bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    analise_end_fact     timestamp(6) without time zone,
    analise_end_plan     timestamp(6) without time zone,
    analise_start_fact   timestamp(6) without time zone,
    analise_start_plan   timestamp(6) without time zone,
    debug_end_fact       timestamp(6) without time zone,
    debug_end_plan       timestamp(6) without time zone,
    debug_start_fact     timestamp(6) without time zone,
    debug_start_plan     timestamp(6) without time zone,
    develop_end_fact     timestamp(6) without time zone,
    develop_end_plan     timestamp(6) without time zone,
    develop_start_fact   timestamp(6) without time zone,
    develop_start_plan   timestamp(6) without time zone,
    issue_prototype_fact timestamp(6) without time zone,
    issue_prototype_plan timestamp(6) without time zone,
    ope_end_fact         timestamp(6) without time zone,
    ope_end_plan         timestamp(6) without time zone,
    ope_start_fact       timestamp(6) without time zone,
    ope_start_plan       timestamp(6) without time zone,
    project_id           bigint,
    rated                boolean,
    release_end_fact     timestamp(6) without time zone,
    release_end_plan     timestamp(6) without time zone,
    release_start_fact   timestamp(6) without time zone,
    release_start_plan   timestamp(6) without time zone,
    stage_zi             integer,
    start_task_fact      timestamp(6) without time zone,
    start_task_plan      timestamp(6) without time zone,
    task                 character varying(255) COLLATE pg_catalog."default",
    release_id           bigint,
    work_id              bigint,
    CONSTRAINT work_project_pkey PRIMARY KEY (id),
    CONSTRAINT fk7awv3x9b6y870qgu0fnsbxsx0 FOREIGN KEY (work_id)
        REFERENCES work_time_project.work (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fknwk9coce1w5u0sa4dcjpcj1n1 FOREIGN KEY (release_id)
        REFERENCES work_time_project.release (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS work_time_project.work_project
    OWNER to postgres;

INSERT INTO work_time_project.work_project(analise_end_fact, analise_end_plan, analise_start_fact, analise_start_plan,
                                           debug_end_fact, debug_end_plan, debug_start_fact, debug_start_plan,
                                           develop_end_fact, develop_end_plan, develop_start_fact, develop_start_plan,
                                           issue_prototype_fact, issue_prototype_plan, ope_end_fact, ope_end_plan,
                                           ope_start_fact, ope_start_plan, project_id, rated, release_end_fact,
                                           release_end_plan, release_start_fact, release_start_plan, stage_zi,
                                           start_task_fact, start_task_plan, task, release_id, work_id)
SELECT w.analise_end_fact,
       w.analise_end_plan,
       w.analise_start_fact,
       w.analise_start_plan,
       w.debug_end_fact,
       w.debug_end_plan,
       w.debug_start_fact,
       w.debug_start_plan,
       w.develop_end_fact,
       w.develop_end_plan,
       w.develop_start_fact,
       w.develop_start_plan,
       w.issue_prototype_fact,
       w.issue_prototype_plan,
       w.ope_end_fact,
       w.ope_end_plan,
       w.ope_start_fact,
       w.ope_start_plan,
       w.project_id,
       w.rated,
       w.release_end_fact,
       w.release_end_plan,
       w.release_start_fact,
       w.release_start_plan,
       w.stage_zi,
       w.start_task_fact,
       w.start_task_plan,
       w.task,
       w.release_id,
       w.id
FROM work_time_project.work w;

-- Column: work_time_project.work.project_list

-- ALTER TABLE IF EXISTS work_time_project.work DROP COLUMN IF EXISTS project_list;

ALTER TABLE IF EXISTS work_time_project."work"
    ADD COLUMN project_list bigint[];

UPDATE work_time_project."work"
SET project_list = '{1}'
WHERE true;
