-- Table: work_time_project.code

-- DROP TABLE IF EXISTS work_time_project.code;

CREATE TABLE IF NOT EXISTS work_time_project.code
(
    id        bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    code      character varying(255) COLLATE pg_catalog."default",
    name      character varying(255) COLLATE pg_catalog."default",
    sort      integer,
    parent_id bigint,
    CONSTRAINT code_pkey PRIMARY KEY (id),
    CONSTRAINT fklopab3u1y8gn63pdhbhyyiq5f FOREIGN KEY (parent_id)
        REFERENCES work_time_project.code (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS work_time_project.code
    OWNER to postgres;

-- Table: work_time_project.code_attr

-- DROP TABLE IF EXISTS work_time_project.code_attr;

CREATE TABLE IF NOT EXISTS work_time_project.code_attr
(
    id      bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    attr    character varying(255) COLLATE pg_catalog."default",
    value   character varying(255) COLLATE pg_catalog."default",
    code_id bigint,
    CONSTRAINT code_attr_pkey PRIMARY KEY (id),
    CONSTRAINT fkr4hin80qjn22lihk2nev3milr FOREIGN KEY (code_id)
        REFERENCES work_time_project.code (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS work_time_project.code_attr
    OWNER to postgres;

-- SEQUENCE: work_time_project.code_attr_id_seq

-- DROP SEQUENCE IF EXISTS work_time_project.code_attr_id_seq;

CREATE SEQUENCE IF NOT EXISTS work_time_project.code_attr_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE work_time_project.code_attr_id_seq
    OWNER TO postgres;

-- SEQUENCE: work_time_project.code_id_seq

-- DROP SEQUENCE IF EXISTS work_time_project.code_id_seq;

CREATE SEQUENCE IF NOT EXISTS work_time_project.code_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE work_time_project.code_id_seq
    OWNER TO postgres;

INSERT INTO work_time_project.code
    (code, name, sort, parent_id)
VALUES ('taskType', 'Справочник типов задач', 10, null),
       ('1', 'ЗИ', 10, 1),
       ('2', 'Вендорные запросы', 40, 1),
       ('3', 'Админ', 50, 1),
       ('4', 'Изменение по ТЗ', 30, 1),
       ('5', 'Запросы по ЗИ', 20, 1),
       ('6', 'Улучшение', 50, 1);

INSERT INTO work_time_project.code_attr
    (attr, value, code_id)
VALUES ('isZI', 'true', 2),
       ('isZI', 'true', 6),
       ('isZI', 'true', 5);

-- Column: work_time_project.task.analyst

-- ALTER TABLE IF EXISTS work_time_project.task DROP COLUMN IF EXISTS analyst;

ALTER TABLE IF EXISTS work_time_project.task
    ADD COLUMN analyst character varying(255) COLLATE pg_catalog."default";

-- Column: work_time_project.task.developer

-- ALTER TABLE IF EXISTS work_time_project.task DROP COLUMN IF EXISTS developer;

ALTER TABLE IF EXISTS work_time_project.task
    ADD COLUMN developer character varying(255) COLLATE pg_catalog."default";

-- Column: work_time_project.task.executor

-- ALTER TABLE IF EXISTS work_time_project.task DROP COLUMN IF EXISTS executor;

ALTER TABLE IF EXISTS work_time_project.task
    ADD COLUMN executor character varying(255) COLLATE pg_catalog."default";

-- Column: work_time_project.task.status

-- ALTER TABLE IF EXISTS work_time_project.task DROP COLUMN IF EXISTS status;

ALTER TABLE IF EXISTS work_time_project.task
    ADD COLUMN status character varying(255) COLLATE pg_catalog."default";

-- Column: work_time_project.task.tester

-- ALTER TABLE IF EXISTS work_time_project.task DROP COLUMN IF EXISTS tester;

ALTER TABLE IF EXISTS work_time_project.task
    ADD COLUMN tester character varying(255) COLLATE pg_catalog."default";