-- SCHEMA: file_repository

-- DROP SCHEMA IF EXISTS file_repository ;

CREATE SCHEMA IF NOT EXISTS file_repository
    AUTHORIZATION postgres;

-- Table: file_repository.file_model

-- DROP TABLE IF EXISTS file_repository.file_model;

CREATE TABLE IF NOT EXISTS file_repository.file_model
(
    id            bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    time_create   timestamp(6) without time zone,
    delete        boolean,
    file_for_disk character varying(255) COLLATE pg_catalog."default",
    file_name     character varying(255) COLLATE pg_catalog."default",
    object_id     character varying(255) COLLATE pg_catalog."default",
    object_type   character varying(255) COLLATE pg_catalog."default",
    size          bigint,
    user_name     character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT file_model_pkey PRIMARY KEY (id)
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS file_repository.file_model
    OWNER to postgres;