-- Table: user_repo.day_info

-- DROP TABLE IF EXISTS user_repo.day_info;

CREATE TABLE IF NOT EXISTS user_repo.day_info
(
    id    bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date  date                                                NOT NULL,
    title character varying(255) COLLATE pg_catalog."default",
    type  character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT day_info_pkey PRIMARY KEY (id),
    CONSTRAINT uk8ciyyq0rxujtpd82sr31ig3ab UNIQUE (date)
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS user_repo.day_info
    OWNER to postgres;