-- Table: user_repo.category

-- DROP TABLE IF EXISTS user_repo.category;

CREATE TABLE IF NOT EXISTS user_repo.category
(
    id     bigint                                              NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name   character varying(255) COLLATE pg_catalog."default" NOT NULL,
    amount double precision                                    NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT uc_category_name UNIQUE (name)
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS user_repo.category
    OWNER to postgres;

-- Column: user_repo.user_info_type.category_id

-- ALTER TABLE IF EXISTS user_repo.user_info_type DROP COLUMN IF EXISTS category_id;

ALTER TABLE IF EXISTS user_repo.users
    ADD COLUMN category_id bigint;