server:
  port: 8188
  servlet:
    context-path: /app
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?options=--search_path=information
    username: postgres
    password: 5397


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

  jackson:
    default-property-inclusion: non_absent

  mail:
    host: smtp.rambler.ru
    port: 465
    #    port: 587
    username: radies@rambler.ru
    password: +!@
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  #           starttls:
  #              enable: true


file:
  save-into: "C:/daru/worktime/mes/"
integration:
  user-service:
    enable: true
  telegram-service:
    enable: false
  calendar-service:
    enable: true
  work-time-service:
    enable: true
  task-service:
    enable: true
  work-service:
    enable: true

