server:
  port: 8188
  servlet:
    context-path: /app
spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?options=--search_path%3Dinformation
    username: postgres
    password: 5397


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

  jackson:
    default-property-inclusion: non_absent
file:
  save-into: "C:/daru/worktime/mes/"
integration:
  user-service:
    enable: true
  telegram-service:
    enable: true
  calendar-service:
    enable: true
  work-time-service:
    enable: true
  task-service:
    enable: true
  work-service:
    enable: true
