-- SCHEMA: max_message

-- DROP SCHEMA IF EXISTS max_message ;

CREATE SCHEMA IF NOT EXISTS max_message
    AUTHORIZATION postgres;

-- Table: max_message.message_receive

-- DROP TABLE IF EXISTS max_message.message_receive;

CREATE TABLE IF NOT EXISTS max_message.message_receive
(
    id                  bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    chat_id             bigint,
    first_name          character varying(255) COLLATE pg_catalog."default",
    is_channel_chat     boolean,
    is_forum            boolean,
    is_group_chat       boolean,
    is_super_group_chat boolean,
    is_user_char        boolean,
    last_name           character varying(255) COLLATE pg_catalog."default",
    text                character varying(4000) COLLATE pg_catalog."default",
    thread_id           integer,
    title               character varying(255) COLLATE pg_catalog."default",
    type                character varying(255) COLLATE pg_catalog."default",
    user_name           character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT message_receive_pkey PRIMARY KEY (id)
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS max_message.message_receive
    OWNER to postgres;

-- Table: max_message.message_send

-- DROP TABLE IF EXISTS max_message.message_send;

CREATE TABLE IF NOT EXISTS max_message.message_send
(
    id        bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    author    character varying(255) COLLATE pg_catalog."default",
    chat_id   character varying(255) COLLATE pg_catalog."default",
    text      character varying(4000) COLLATE pg_catalog."default",
    thread_id integer,
    CONSTRAINT message_send_pkey PRIMARY KEY (id)
)
    TABLESPACE pg_default;

ALTER TABLE IF EXISTS max_message.message_send
    OWNER to postgres;